apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lets-chat-mongo
  labels:
    app: lets-chat
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lets-chat
        tier: backend
    spec:
      containers:
      - name: lets-chat-mongo
        image: "mongo:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    tier: backend
spec:
  selector:
    app: lets-chat
    tier: backend
  ports:
  - port: 27017
