apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lets-chat-app
  labels:
    app: lets-chat
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lets-chat
        tier: frontend
    spec:
      containers:
      - name: lets-chat-app
        image: "sdelements/lets-chat:latest"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongo-settings
          mountPath: /usr/src/app/config
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: LCB_DATABASE_URI
          value: mongodb://db/letschat
      volumes:
        - name: mongo-settings
          configMap:
            name: mongo-settings
---
apiVersion: v1
kind: Service
metadata:
  name: lets-chat-app
  labels:
    app: lets-chat
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30303
  selector:
    app: lets-chat
    tier: frontend
