apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
    tier: frontend
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}-app
        image: "sdelements/lets-chat:{{ .Chart.Version }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongo-settings
          mountPath: /usr/src/app/config/settings.yml
        ports:
        - name: http
          containerPort: 8080
